[package]
name = "steamdeck_sd_card_scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.6"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
dirs = "4"